[project]
name = "stcodegenerate"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "aiofiles>=25.1.0",
    "jinja2>=3.1.6",
    "openai>=2.21.0",
    "pyyaml>=6.0.3",
]
